{% set name = "pylint-common" %}
{% set version = "0.2.5" %}
{% set sha256 = "3276b9e4db16f41cee656c78c74cfef3da383e8301e5b3b91146586ae5b53659" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - pylint >=1.0
    - pylint-plugin-utils >=0.2.6

test:
  imports:
    - pylint_common

about:
  home: https://github.com/landscapeio/pylint-common
  license: GPL 2
  license_file: LICENSE
  summary: 'pylint-common is a Pylint plugin to improve Pylint error analysis of the standard Python library'

extra:
  recipe-maintainers:
    - jakirkham
