travis:
  secure:
    BINSTAR_TOKEN: IdgFfZAV4V6uKqaXALnoNPtXZDoVnMCBh6R+GpkXeVIV7gex2Gpg/cCVYMTGxFYo/UpaVlTTk7PmA1JiuYvApTuSFUDWtDjz06UDVbg6ybaBPmtP1IY/zqCqUrk3RDA/gvarg4pInYLXzRqRMHYWvpZWUD0YGZN//hVyQoDvM0XizXAuUzVMK1OMhtexLy0r21SFwCdw6MCcGqOItoWte6WU0Gufvv035GOW2LgruCrprsCTaUm1Q1VI6Cp35LUYLLRIHQDMYBWbzZu7ohN64g1BQqMsXS/RLi7RJcEJodRC6y+nZWKqqXwMeUDe2gujDcDabkiIjTgNHIWOXDlov/i6Dswize/PtT5PrOSRcFCAOhsGjvkBvcC61dUh4Bd8WNj2xgs7LKmh5LtY4bfi8PyUssoqUGpKcztVxVOud4Ty4GuAg1eyjYl9WmENN8F7bcnYUjVAKHPyh2ISB3kxvmClfwnUfzwNjQX8ospjie5gnfehFX7BBj/HoyB2lKk5MpVbX0Vm7WkJNaqAaPa+TD6u28+PrQuSVMJlIbUGXbyyANke4Twugz8Dl7YR8DJeCjIrgptc0Nk/+jdGkaOxEoGdZGxGVyjbcCJ3wp+uDN5NeELCAg210JMf2NtmQR2zNbcRRUmCj2rGWCe5aTOhoF9JGXFdSfTCiPl33z+E8yY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
