travis:
  secure:
    BINSTAR_TOKEN: 4RTClbKXwgJcl6t8CZJknhkM2H7r3Tfpz6tX8oApi07w5hM1LzPXySZ6oYwNP5SpBX4WsLJm5N3tRHD2aks7Es3fSdMOK2NS9Ofh3hohhSjaQctEVs8GDh6fX5IDmHhiuczAFnaUD68tGrfprqWJAcfqlP3ZiSLSL5N5VgiS/69Rv5HnJDGRz5SYaG8NyBflwQU9J55morKszLVqMtQ18/rZdvg32jlB9PgU3NC5yCXE6P1RqE7aCtCWOXBMlxQk+Be3wsbdWzsTpwTYOdFMxEZlFoWvof6Wst4VKI1z9IDTvgjGna0CrzX6DbNWKgRz3/TmcpEnoH0svdRLRYZwuLDve43XmKy1kV4DlZnzyN0wwgquZ9pyXrs+sBYy0+ElMkwlAKlGEX1pgJd0XJ38kMbgVbA9M7hewHmpmsz5Aop9OSMH2G0IQrqAbWfet/KOY9payqL1sDm5c92Z9suEtArvq6RGGayCg5HIeiKzsVRu1CTxQcyOuKIUnZBw6OEoNq9NwE/G3l4q3pEvYeNzbg+lD8bBCqS/vEzFF8y6u2vw6dS8Rc+McCNZcVWoQ/7nB2GjkK/KgGk7sjZqRndexm9HEn5P9v0Jd6igM/kehW8osM9ikazPom+/PXWVIUHdiZBikoK2A2gxjvAejbQPsSqLs9g1XrmIGv+3D5RqSOM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
